### ISSUE TITLE
Getting validateDOMNesting(...): <button> cannot appear as a descendant of <button> error when datepicker modal is oppened on web

### ISSUE THREAD

**Issue by daxazala** [web-ridge/react-native-paper-dates#323]
### Current behaviour
i am using datepicker modal from react native paper dates and recently updated the libraries with latest versions and then i tried to run the app and noticed below error
react-dom.development.js:86 Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.
    at button
    at http://localhost:19006/static/js/bundle.js:19090:25
    at Pressable (http://localhost:19006/static/js/bundle.js:15866:24)
    at TouchableRipple (http://localhost:19006/static/js/bundle.js:11421:20)
    at div
    at http://localhost:19006/static/js/bundle.js:19090:25
    at http://localhost:19006/static/js/bundle.js:25359:90
    at http://localhost:19006/static/js/bundle.js:8520:31
    at http://localhost:19006/static/js/bundle.js:7453:19
    at div
    at http://localhost:19006/static/js/bundle.js:19090:25

### How to reproduce?
you can reproduce the issue by taking the latest version of react native paper dates and run the examples on web and you can see the issue in browser console.
1.clone react native paper dates repo
2. then build the project and run web script under examples folder
3. go to browser where you web app is running and click calendar button as shown in below screenshot and you will be able to see the error in console.

### Your Environment

| software                      | version
| --------------------- | -------
| react-native                | 0.72.4
| react-native-paper      |  ^5.10.3
| react-native-web         | 0.19.8
| node                           | v18.12.1 
| npm or yarn                | v8.19.3(npm)
| expo sdk                     | ^49.0.9

![rnpd-issue-2](https://github.com/web-ridge/react-native-paper-dates/assets/69502463/956be846-c620-4f63-a57c-2dbed1c7c4a9)
![rnpd-issue-1](https://github.com/web-ridge/react-native-paper-dates/assets/69502463/8903518c-8c13-44e7-bbc1-eaaa3580e406)

**Comment by davidmartinrius** [comment]
Hello, same error here in react native web + rn paper. Did you find any solution?

**Comment by iM-GeeKy** [comment]
PRs are welcome!

**Comment by kebarvid** [comment]
Have the same issue. Isn't a repro provided in the first post?

**Comment by Martijncvv** [comment]
Same problem:
  "react-native": "0.72.6",
      "expo": "~49.0.13",
        "react-native-paper-dates": "^0.19.7",

**Comment by jweihsSF** [comment]
The issue still occurs, but I don't have a solution yet.

**Comment by RichardLindhout** [comment]
Fixed!

**Comment by 123zarif** [comment]
Still getting the error

**Comment by 123zarif** [comment]
Anyone else getting the same error?

**Comment by schtiefel** [comment]
Yes, still getting the error.

react-native-paper-dates: 0.21.7
react-native-paper: 5.11.0
react-native: 0.72.6
react-native-web: 0.19.9

**Comment by yngfoxx** [comment]
I have replaced the IconButton with just the Icon component

**Comment by RichardLindhout** [comment]
Really cool! The icon component did not exist when I created this library :)

**Comment by RichardLindhout** [comment]
@schtiefel @123zarif the https://github.com/web-ridge/react-native-paper-dates/releases/tag/v0.21.8 by @yngfoxx should fix this issue :)
